### ISSUE TITLE
同求修复，删了后重新fork也会报错😊

### ISSUE THREAD

**Issue by 123456563** [LihaoLikeOrangeJuice/clockIn_gzhu#6]

**Comment by LihaoLikeOrangeJuice** [comment]
现在应该行了。之前报错是因为健康打卡多了一个必填项

**Comment by LihaoLikeOrangeJuice** [comment]
忘了说了，因为多了一个必填项，所以还要再加一个Repository secret，你看简介就知道怎么设置了

**Comment by LihaoLikeOrangeJuice** [comment]
你设置了LOCATION这个Secret吗

**Comment by 123456563** [comment]
没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LihaoLikeOrangeJuice/clockIn_gzhu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 晚上8:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LihaoLikeOrangeJuice/clockIn_gzhu] 同求修复，删了后重新fork也会报错😊 (Issue #6)





 
你设置了LOCATION这个Secret吗

**Comment by 123456563** [comment]
好的多谢，我重试一下





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lihao ***@***.***&gt;; 
发送时间: 2022年6月1日(星期三) 下午5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LihaoLikeOrangeJuice/clockIn_gzhu] 同求修复，删了后重新fork也会报错😊 (Issue #6)





 
现在应该行了。之前报错是因为健康打卡多了一个必填项
