### ISSUE TITLE
不知道为啥。。。又报错了

### ISSUE THREAD

**Issue by 123456563** [LihaoLikeOrangeJuice/clockIn_gzhu#8]

**Comment by LihaoLikeOrangeJuice** [comment]
或许是学校服务器崩溃了

**Comment by 123456563** [comment]
可以手动打卡，然后我重新fork后还是不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lihao ***@***.***&gt;; 
发送时间: 2022年6月5日(星期天) 下午3:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LihaoLikeOrangeJuice/clockIn_gzhu] 不知道为啥。。。又报错了 (Issue #8)





 
或许是学校服务器崩溃了

**Comment by LihaoLikeOrangeJuice** [comment]
我刚刚运行了一遍，能正常运行
